import type { Destination, DestinationId } from '@/types';

export const DESTINATIONS: readonly Destination[] = [
  {
    id: 'origin',
    name: 'The Origin',
    designation: 'CA-01 / HOME WORLD',
    role: 'Welcome',
    position: [0, 0, 0],
    radius: 9,
    orbitRadius: 58,
    orbitSpeed: 0.014,
    rotationSpeed: 0.055,
    surface: ['#0a2a52', '#1f6fb8', '#8fdcff'],
    atmosphere: '#6CF6FF',
    emissive: 0.16,
    cloudOpacity: 0.42,
    hidden: false,
    rings: [
      {
        innerRadius: 12.5,
        outerRadius: 16.5,
        tilt: 0.42,
        opacity: 0.32,
        color: '#8ad6ff',
      },
    ],
    moons: [
      { radius: 1.5, distance: 20, speed: 0.32, inclination: 0.25, color: '#cfe4ff' },
      { radius: 0.9, distance: 27, speed: 0.19, inclination: -0.42, color: '#9fb4d8' },
    ],
    tagline: 'Where the archive begins.',
    ambience: 'Cool mist, aurora at both poles, two quiet moons.',
  },
  {
    id: 'observatory',
    name: 'The Observatory',
    designation: 'CA-02 / RESEARCH WORLD',
    role: 'Work',
    position: [0, 0, 0],
    radius: 7.4,
    orbitRadius: 104,
    orbitSpeed: 0.0093,
    rotationSpeed: 0.031,
    surface: ['#0d1424', '#2b3d63', '#7ba0ff'],
    atmosphere: '#3E74FF',
    emissive: 0.34,
    cloudOpacity: 0.1,
    hidden: false,
    rings: [
      {
        innerRadius: 10.4,
        outerRadius: 12.2,
        tilt: -0.62,
        opacity: 0.5,
        color: '#6CF6FF',
      },
      {
        innerRadius: 13.2,
        outerRadius: 14.1,
        tilt: -0.62,
        opacity: 0.22,
        color: '#6D5DF6',
      },
    ],
    moons: [{ radius: 0.8, distance: 17, speed: 0.44, inclination: 0.6, color: '#6CF6FF' }],
    tagline: 'Instruments pointed at everything we have built.',
    ambience: 'Dark metallic crust, energy beams, holographic displays in orbit.',
  },
  {
    id: 'library',
    name: 'The Library Moon',
    designation: 'CA-03 / ARCHIVE BODY',
    role: 'About',
    position: [0, 0, 0],
    radius: 6.1,
    orbitRadius: 152,
    orbitSpeed: 0.0068,
    rotationSpeed: 0.022,
    surface: ['#141a2e', '#3e5f57', '#a8f5d0'],
    atmosphere: '#7AF5FF',
    emissive: 0.28,
    cloudOpacity: 0.22,
    hidden: false,
    rings: [],
    moons: [
      { radius: 0.6, distance: 12, speed: 0.52, inclination: 0.9, color: '#a8f5d0' },
      { radius: 0.45, distance: 15.5, speed: -0.38, inclination: 0.3, color: '#ffd76a' },
    ],
    tagline: 'Crystal forests that remember every version of the story.',
    ambience: 'Aurora green haze, drifting glass books, low fog over ruins.',
  },
  {
    id: 'gallery',
    name: 'The Nebula Gallery',
    designation: 'CA-04 / EXHIBITION FIELD',
    role: 'Gallery',
    position: [0, 0, 0],
    radius: 10.6,
    orbitRadius: 206,
    orbitSpeed: 0.0049,
    rotationSpeed: 0.017,
    surface: ['#22103f', '#5c2f8f', '#c79bff'],
    atmosphere: '#7A4DFF',
    emissive: 0.3,
    cloudOpacity: 0.55,
    hidden: false,
    rings: [
      {
        innerRadius: 14.5,
        outerRadius: 21,
        tilt: 0.28,
        opacity: 0.38,
        color: '#c79bff',
      },
    ],
    moons: [{ radius: 1.1, distance: 26, speed: -0.22, inclination: -0.15, color: '#e6d2ff' }],
    tagline: 'Frames suspended in violet dust.',
    ambience: 'Nebula dust, slow violet weather, glass frames adrift.',
  },
  {
    id: 'comms',
    name: 'Communication Station',
    designation: 'CA-05 / ORBITAL RELAY',
    role: 'Contact',
    position: [0, 0, 0],
    radius: 5.2,
    orbitRadius: 258,
    orbitSpeed: 0.0037,
    rotationSpeed: 0.048,
    surface: ['#2a1414', '#7a3b2a', '#ffb27a'],
    atmosphere: '#FFD76A',
    emissive: 0.42,
    cloudOpacity: 0.08,
    hidden: false,
    rings: [
      {
        innerRadius: 7.4,
        outerRadius: 9.6,
        tilt: 1.24,
        opacity: 0.44,
        color: '#FFD76A',
      },
    ],
    moons: [
      { radius: 0.4, distance: 10, speed: 0.8, inclination: 1.1, color: '#ffd76a' },
      { radius: 0.35, distance: 12.5, speed: -0.66, inclination: 0.2, color: '#ff9a6a' },
    ],
    tagline: 'Transmission window is open.',
    ambience: 'Volcanic ash, rotating antennae, drones on maintenance loops.',
  },
  {
    id: 'frost',
    name: 'The Frozen Moon',
    designation: 'CA-06 / SEALED BODY',
    role: 'Secret',
    position: [0, 0, 0],
    radius: 4.4,
    orbitRadius: 178,
    orbitSpeed: 0.0058,
    rotationSpeed: 0.012,
    surface: ['#0e1b2a', '#3d6b8c', '#eaf7ff'],
    atmosphere: '#7AF5FF',
    emissive: 0.1,
    cloudOpacity: 0.14,
    hidden: true,
    unlockedBy: 'asteroid-relic',
    rings: [],
    moons: [],
    tagline: 'Methane plains that have not moved in a long time.',
    ambience: 'No weather. No signal. A surface that records every impact.',
  },
  {
    id: 'crystal',
    name: 'The Crystal World',
    designation: 'CA-07 / RESONANT BODY',
    role: 'Secret',
    position: [0, 0, 0],
    radius: 7.8,
    orbitRadius: 232,
    orbitSpeed: 0.0042,
    rotationSpeed: 0.038,
    surface: ['#1a1030', '#6a3f9e', '#ffd6f5'],
    atmosphere: '#c79bff',
    emissive: 0.55,
    cloudOpacity: 0.05,
    hidden: true,
    unlockedBy: 'satellite-signal',
    rings: [
      {
        innerRadius: 10.5,
        outerRadius: 13.8,
        tilt: -0.9,
        opacity: 0.4,
        color: '#ffd6f5',
      },
    ],
    moons: [
      { radius: 0.5, distance: 16, speed: 0.7, inclination: 1.3, color: '#ffd6f5' },
    ],
    tagline: 'The whole crust rings at one frequency.',
    ambience: 'Lattice growth visible from orbit, faint standing harmonic.',
  },
  {
    id: 'quantum',
    name: 'The Quantum Anomaly',
    designation: 'CA-08 / UNRESOLVED',
    role: 'Secret',
    position: [0, 0, 0],
    radius: 5.6,
    orbitRadius: 292,
    orbitSpeed: 0.0027,
    rotationSpeed: 0.09,
    surface: ['#04121a', '#0f7a7a', '#9dfff0'],
    atmosphere: '#6CF6FF',
    emissive: 0.78,
    cloudOpacity: 0.32,
    hidden: true,
    unlockedBy: 'code-archive',
    rings: [],
    moons: [
      { radius: 0.4, distance: 11, speed: 1.4, inclination: 0.4, color: '#9dfff0' },
      { radius: 0.4, distance: 11, speed: -1.4, inclination: -0.4, color: '#9dfff0' },
    ],
    tagline: 'Observed twice, measured differently each time.',
    ambience: 'Position is probabilistic. Both moons may be the same moon.',
  },
  {
    id: 'blackhole',
    name: 'The Black Hole',
    designation: 'CA-∞ / ANOMALY',
    role: 'Secret',
    position: [0, 0, 0],
    radius: 12,
    orbitRadius: 330,
    orbitSpeed: 0.0016,
    rotationSpeed: 0.008,
    surface: ['#000000', '#1a0b2e', '#ff9d4d'],
    atmosphere: '#FFD76A',
    emissive: 1,
    cloudOpacity: 0,
    hidden: true,
    rings: [],
    moons: [],
    tagline: 'Spacetime does not resolve here.',
    ambience: 'Gravitational lensing, accretion glow, distorted physics.',
  },
] as const;

export const DESTINATION_MAP: Readonly<Record<DestinationId, Destination>> =
  DESTINATIONS.reduce(
    (acc, destination) => {
      acc[destination.id] = destination;
      return acc;
    },
    {} as Record<DestinationId, Destination>,
  );

export const VISIBLE_DESTINATIONS = DESTINATIONS.filter((d) => !d.hidden);

export const DEFAULT_DESTINATION: DestinationId = 'origin';

/** Orbital phase offsets keep the planets from ever lining up in a straight row. */
export const ORBIT_PHASE: Readonly<Record<DestinationId, number>> = {
  origin: 0.6,
  observatory: 2.35,
  library: 4.1,
  gallery: 5.6,
  comms: 1.35,
  blackhole: 3.2,
  frost: 0.15,
  crystal: 4.85,
  quantum: 2.05,
};
